services:
  db:
    image: mysql:8.0.39
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_ARBITRARY=1

  redis:
    image: redis:7.0.15
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/volumes/mysql/data
